### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by HarrialX** [michiyasunaga/DrRepair#6]
Hi, Dear Author @michiyasunaga, I successfully downloaded the datasets and tried to understand JSON's internal contents. If understand correctly, are the codes in X['lines'] are fixed codes? 

I also found that each program (in a single json file) has a lot groups of buggy information by ["err_line", "err_msg", "mod_line", "mod_code"]. If my understanding is correct, when using the workable program in X['lines'], we can independently generate multiple buggy codes by each group of ["err_line", "err_msg", "mod_line", "mod_code"], is that a correct usage?

**Comment by michiyasunaga** [comment]
Yes, that is correct.
